name: Deploy to GCP

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發部署

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Output secrets for debugging
      run: |
        echo "GCP_VM_USER: ${{ secrets.GCP_VM_USER }}"
        echo "GCP_VM_IP: ${{ secrets.GCP_VM_IP }}"
        # 不建議輸出私鑰，這裡僅作為示範，實際應避免
        echo "GCP_SSH_PRIVATE_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}" | head -c 20
      shell: bash
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 34.172.22.249 >> ~/.ssh/known_hosts

    - name: Deploy to GCP VM
      run: |
        rsync -avz --exclude='.git' -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }}:/home/haoyu6875/flask
        ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
          source ~/.bashrc
          conda activate teeth  # 激活你的 conda 虛擬環境
          cd /home/haoyu6875/flask
          # pip install -r requirements.txt
          sudo systemctl restart flaskapp  # 重啟服務
        EOF
